# quarry — install helpers. Dependency-free; installs by symlinking bin/quarry
# onto your PATH and dropping shell-completion files into per-shell user dirs.
#
#   make install               symlink `quarry` into BINDIR
#   make install-completions   install fish/zsh/bash completions
#   make install-config        drop a starter config (won't clobber an existing one)
#   make test                  run the unit test suite
#   make uninstall             remove everything the above installed
#
# Override any directory on the command line, e.g.:
#   make install PREFIX=/usr/local

PREFIX   ?= $(HOME)/.local
BINDIR   ?= $(PREFIX)/bin

FISH_DIR ?= $(HOME)/.config/fish/completions
ZSH_DIR  ?= $(PREFIX)/share/zsh/site-functions
BASH_DIR ?= $(PREFIX)/share/bash-completion/completions

# Search config lives under XDG config home (honored by quarry itself too).
CONFIG_DIR ?= $(or $(XDG_CONFIG_HOME),$(HOME)/.config)/quarry

# Absolute path to the entry point, so the symlink works from any cwd. quarry-fzf
# is found as its sibling in bin/, so only `quarry` needs to be on PATH.
QUARRY  := $(abspath bin/quarry)
EXAMPLE := $(abspath config.ini.example)
PYTHON  ?= python3

# Generated, untracked: records the commit `make install` pinned, so that
# `quarry --version` can report it without shelling out to git.
STAMP   ?= $(abspath src/build_stamp.py)

# Which field `make release` advances: major, minor or patch.
BUMP    ?= minor
BUMPER  := $(abspath tools/bump_version.py)

# Python invalidates cached bytecode on mtime and size, and two stamps differ
# in neither, so a regenerated stamp can be masked by the previous one's .pyc.
STAMP_PYC := $(dir $(STAMP))__pycache__/$(basename $(notdir $(STAMP))).*.pyc

.DEFAULT_GOAL := help

.PHONY: help install uninstall install-completions install-config test stamp \
        release install-fish install-zsh install-bash

help:
	@echo "quarry — make targets:"
	@echo "  install               symlink quarry into $(BINDIR)"
	@echo "  install-completions   install fish/zsh/bash completions"
	@echo "  install-config        drop a starter config (won't clobber existing)"
	@echo "  test                  run the unit test suite"
	@echo "  stamp                 re-pin the commit that --version reports"
	@echo "  release               bump the version, commit it and tag it"
	@echo "                        (BUMP=major|minor|patch, default $(BUMP))"
	@echo "  uninstall             remove the symlink and completion files"
	@echo ""
	@echo "Dirs (override on the command line): PREFIX=$(PREFIX)"

test:
	@$(PYTHON) -m unittest discover -s tests -p 'test_*.py'

# Pin the commit that --version reports, and how many commits it sits past the
# newest release tag — that count is what makes --version move between
# releases. Outside a git checkout there is nothing to read, so the stamp is
# skipped and --version prints just the version number.
stamp:
	@if git -C "$(CURDIR)" rev-parse HEAD >/dev/null 2>&1; then \
	  printf '%s\n%s\n\n' \
	    '# PURPOSE: Names the commit this quarry was installed from, so that' \
	    '# --version needn'\''t run git. Generated by `make stamp`; not tracked.' \
	    > "$(STAMP)"; \
	  git -C "$(CURDIR)" log -1 --format='DATE = "%cs"%nCOMMIT = "%h"' >> "$(STAMP)"; \
	  tag="$$(git -C "$(CURDIR)" describe --tags --abbrev=0 2>/dev/null)"; \
	  if [ -n "$$tag" ]; then \
	    ahead="$$(git -C "$(CURDIR)" rev-list --count "$$tag"..HEAD)"; \
	    since="$$ahead commit(s) past $$tag"; \
	  else \
	    ahead=0; \
	    since="no release tag yet"; \
	  fi; \
	  echo "COMMITS_SINCE_RELEASE = $$ahead" >> "$(STAMP)"; \
	  rm -f $(STAMP_PYC); \
	  echo "stamp: pinned $$(git -C "$(CURDIR)" log -1 --format='%h (%cs)') — $$since"; \
	else \
	  echo "stamp: not a git checkout — skipped; --version reports the version only"; \
	fi

# Cut a release: advance the version constant, commit that one line, tag it.
#   make release              0.1.0 -> 0.2.0
#   make release BUMP=major   0.1.0 -> 1.0.0
#   make release BUMP=patch   0.1.0 -> 0.1.1
# Nothing is pushed — publishing the tag stays a deliberate, separate step,
# since a tag other people have fetched is not reasonably retractable.
release:
	@test -z "$$(git -C "$(CURDIR)" status --porcelain)" \
	  || { echo "release: working tree is dirty — commit or stash first" >&2; exit 1; }
	@new="$$($(PYTHON) "$(BUMPER)" $(BUMP) --file "$(QUARRY)" --print)" || exit 1; \
	if git -C "$(CURDIR)" rev-parse -q --verify "refs/tags/v$$new" >/dev/null; then \
	  echo "release: tag v$$new already exists" >&2; exit 1; \
	fi; \
	$(PYTHON) "$(BUMPER)" $(BUMP) --file "$(QUARRY)" >/dev/null \
	  && git -C "$(CURDIR)" commit -q -m "version: $$new" -- "$(QUARRY)" \
	  && git -C "$(CURDIR)" tag -a "v$$new" -m "quarry $$new" \
	  && echo "release: committed and tagged v$$new" \
	  && echo "         publish with: git push --follow-tags"
	@$(MAKE) --no-print-directory stamp

install: stamp
	@mkdir -p "$(BINDIR)"
	@ln -sf "$(QUARRY)" "$(BINDIR)/quarry"
	@echo "installed: $(BINDIR)/quarry -> $(QUARRY)"
	@case ":$$PATH:" in *":$(BINDIR):"*) ;; \
	  *) echo "note: $(BINDIR) is not on your PATH — add it to use \`quarry\`." ;; esac
	@echo "next: make install-completions"

# fish autoloads this directory, so no rc edit is needed.
install-fish:
	@mkdir -p "$(FISH_DIR)"
	@"$(QUARRY)" completions fish > "$(FISH_DIR)/quarry.fish"
	@echo "fish: installed $(FISH_DIR)/quarry.fish (autoloads; open a new shell)"

# zsh needs the containing dir on $fpath before compinit runs.
install-zsh:
	@mkdir -p "$(ZSH_DIR)"
	@"$(QUARRY)" completions zsh > "$(ZSH_DIR)/_quarry"
	@echo "zsh: installed $(ZSH_DIR)/_quarry"
	@echo "     add to ~/.zshrc BEFORE 'compinit':"
	@echo "       fpath+=($(ZSH_DIR)); autoload -Uz compinit && compinit"

# bash-completion (v2) autoloads this XDG dir; otherwise source the file directly.
install-bash:
	@mkdir -p "$(BASH_DIR)"
	@"$(QUARRY)" completions bash > "$(BASH_DIR)/quarry"
	@echo "bash: installed $(BASH_DIR)/quarry"
	@echo "     if you don't use bash-completion, add to ~/.bashrc:"
	@echo "       source $(BASH_DIR)/quarry"

install-completions: install-fish install-zsh install-bash

# Starter config, only if the user has none — never overwrite their settings.
install-config:
	@mkdir -p "$(CONFIG_DIR)"
	@if [ -e "$(CONFIG_DIR)/config.ini" ]; then \
	  echo "config: $(CONFIG_DIR)/config.ini exists — left unchanged"; \
	else \
	  cp "$(EXAMPLE)" "$(CONFIG_DIR)/config.ini"; \
	  echo "config: installed $(CONFIG_DIR)/config.ini"; \
	fi

uninstall:
	@rm -f "$(STAMP)" \
	       "$(BINDIR)/quarry" \
	       "$(FISH_DIR)/quarry.fish" \
	       "$(ZSH_DIR)/_quarry" \
	       "$(BASH_DIR)/quarry"
	@echo "removed quarry symlink and completion files"
